- name: install mysql
  #ansible.builtin.dnf:
  dnf:
    name: mysql-server
    state: latest

- name: start and enable mysql
  #ansible.builtin.service:
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Install Python Dependencies
  ansible.builtin.pip:
    name: 
    - PyMySQL   
    - cryptography
    executable: pip3.9   

- name: checking mysql root setup or NoT
  #community.mysql.mysql_info:
  mysql_info:
    login_user: "{{user}}"
    login_password: "{{password}}"
    login_host: "{{DB_HOST}}"
    filter: version
  ignore_errors: yes
  register: mysql_connection_output

- name: Print Output
  debug:
    msg: "LogIn OutPut is: {{mysql_connection_output}} "     

- name: Setup mysql root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{password}}   
  when: mysql_connection_output.failed is true     